name: sales_report_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  json_annotation: ^4.8.0
  cloud_firestore: ^4.5.0
  get_cli: ^1.8.1
  dropdown_search: ^5.0.6
  intl: ^0.18.1
  date_field: ^3.0.5
  grouped_list: ^5.1.2
  font_awesome_flutter: ^10.5.0

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.6.1

flutter: 
  uses-material-design: true

  assets:
    - asset/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins-Regular.ttf
        - asset: asset/font/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/Poppins-SemiBold.ttf
          weight: 600